export const NigeriaStateCityMap: Record<string, string[]> = {
  Abia: ['Aba', 'Umuahia'],
  Anambra: ['Onitsha', 'Awka'],
  Adamawa: ['Yola'],
  AkwaIbom: ['Uyo', 'Ikot Ekpene', 'Abak', 'Eket', 'Itu'],
  Bauchi: ['Bauchi'],
  Bayelsa: ['Yenagoa'],
  Benue: ['Makurdi'],
  Borno: ['Maiduguri'],
  CrossRiver: ['Calabar', 'Ikom', 'Ogoja'],
  Delta: ['Asaba', 'Warri', 'Sapele', 'Ugheli', 'Aboh'],
  Ebonyi: ['Abakaliki'],
  Edo: ['Benin City', 'Ekpoma', 'Auchi'],
  Ekiti: ['Ado-Ekiti'],
  Enugu: ['Enugu', 'Nsukka', 'Oji River'],
  Gombe: ['Gombe'],
  Imo: ['Owerri'],
  Jigawa: ['Dutse'],
  Kaduna: ['Kaduna', 'Zaria'],
  Kano: ['Kano'],
  Katsina: ['Katsina'],
  Kebbi: ['Birnin Kebbi'],
  Kogi: ['Lokoja', 'Okene', 'Ajaokuta'],
  Kwara: ['Ilorin'],
  Lagos: [
    'Ikeja',
    'Surulere',
    'Obalende',
    'Ikoyi',
    'Victoria Island',
    'Lekki',
    'Ajah',
    'Agege',
    'Ojodu Berger',
    'Festac Town',
    'Kosofe',
    'Oshodi',
    'Isolo',
    'Apapa',
    'Ojo',
    'Mushin',
    'Lekki Epe Express Way',
    'Mobolaji Bank Anthony',
    'Local Airport',
    'International Airport Road',
    'Allen Avenue',
    'Obafemi Awolowo Way',
    'Oregun',
    'Shomolu',
    'Lagos Mainland',
    'Iponri-Costain',
    'Ogunlana-Drive',
    'Ogba',
    'Ifako',
    'Ikorodu',
    'Ketu',
    'Lagos Ibadan Express Way',
    'Epe',
    'Ibeju Lekki',
    'Badagry',
  ],
  Nasarawa: ['Lafia', 'Karu', 'Keffi'],
  Niger: ['Minna', 'Suleja', 'Bida'],
  Ogun: [
    'Abeokuta',
    'Sagamu',
    'Ijebu Ode',
    'Sango Ota',
    'Mowe',
    'Ibafo',
    'Ikene',
  ],
  Ondo: ['Akure', 'Owo', 'Ondo'],
  Osun: ['Osogbo', 'Ife', 'Ilesa', 'Ikire'],
  Oyo: ['Ibadan', 'Ogbomoso'],
  Plateau: ['Jos', 'Langtang', 'Barkin Ladi'],
  Rivers: [
    'Port Harcourt',
    'Rumuokoro',
    'Onne',
    'Ikwere',
    'Airport Road',
    'Port-Aba Road',
    'Omagwa International Airport',
    'Ahoada',
    'Abonnema',
  ],
  Sokoto: ['Sokoto'],
  Taraba: ['Jalingo'],
  Yobe: ['Damaturu'],
  Zamfara: ['Gusau'],
  FCT: [
    'Garki',
    'Wuse',
    'Jabi',
    'Maitama',
    'Gwarimpa',
    'Asokoro',
    'Nyanya',
    'Karu',
    'Kubwa',
    'Jukwoyi',
    'Durumi',
    'Kukwaba',
    'Gudu',
    'Wuye',
    'Utako',
    'Abaji',
    'Bwari',
    'Gwagwalada',
    'Kuje',
    'Kwali',
    'Lugbe',
  ],
};
